spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:configserver:http://config-server:8080
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  vector
api:
  key: ${API_KEY}
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
        web:
          client: DEBUG
        http:
          client: DEBUG