spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:configserver:http://config-server:8080
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        sendVerificationCode-out-0:
          destination: send-verification-code-topic
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA}
  batch:
    initialize-schema: always
    job:
      enabled: false
  jpa:
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-filesystem
              root: ./data/index
          schema_management:
            strategy: create-or-validate
jwt:
  secret: ${JWT_SECRET}
  expirationTime: 3600000
  authorizationHeader: ${AUTH_HEADER}
  refreshToken:
    expirationTime: 259200000
verification:
  codeTTL: 180
  tokenTTL: 120
api:
  key: ${API_KEY}
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000