version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - unihub

  config-server:
    image: unihub/config:s1
    container_name: config-server
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    env_file:
      - ../../config/.env
    networks:
      - unihub

  eureka-server:
    image: unihub/eureka:s1
    container_name: eureka-server
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    env_file:
      - ../../eureka/.env
    networks:
      - unihub

  gateway-server:
    image: unihub/gateway:s1
    container_name: gateway-server
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    env_file:
      - ../../gateway/.env
    networks:
      - unihub

networks:
  unihub:
    driver: bridge
