spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:configserver:http://config-server:8080
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000